# Generated by Django 4.2.4 on 2023-08-17 16:04

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('conversation', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ConversatioMessage',
            new_name='ConversationMessage',
        ),
    ]
